-- DDL

DROP DATABASE IF EXISTS venta_libros ;

CREATE DATABASE venta_libros;

USE venta_libros;

-- Tabla VENTA
CREATE TABLE VENTA (
    IDVENTA INT PRIMARY KEY AUTO_INCREMENT,
    IDCLIENTE INT,
    IDLIBRO INT,
    IDEMPLEADO INT,
    IDTIPOVENTA INT,
    FECHA DATETIME
);                                                

-- Tabla CLIENTE
CREATE TABLE CLIENTE (
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) DEFAULT 'USUARIO_UNKNOW',
    TELEFONO VARCHAR(20) NOT NULL,
    CORREO VARCHAR(100) UNIQUE NOT NULL,
    FECHA_ALTA DATETIME DEFAULT (CURRENT_TIMESTAMP),
    STATUS BOOLEAN DEFAULT TRUE
);

-- Tabla EMPLEADO
CREATE TABLE EMPLEADO (
    IDEMPLEADO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    TELEFONO VARCHAR(20),
    CORREO VARCHAR(100),
    IDSUCURSAL INT
);

-- Tabla GERENTE
CREATE TABLE GERENTE (
    IDGERENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    TELEFONO VARCHAR(20),
    CORREO VARCHAR(100)
);

-- Tabla TIPOVENTA
CREATE TABLE TIPOVENTA (
    IDTIPOVENTA INT PRIMARY KEY AUTO_INCREMENT,
    TIPO VARCHAR(50)                                
);

-- Tabla SUCURSAL
CREATE TABLE SUCURSAL (
    IDSUCURSAL INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(20),
    IDGERENTE INT
);

-- Tabla LIBRO
CREATE TABLE LIBRO (
    IDLIBRO INT PRIMARY KEY AUTO_INCREMENT,
    IDSUCURSAL INT,
    IDPROVEEDOR INT,
    TITULO VARCHAR(100),
    PRECIO_UNITARIO INT,
    DISPONIBLE BOOLEAN
);

-- Tabla PROVEEDOR
CREATE TABLE PROVEEDOR (
    IDPROVEEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    TELEFONO VARCHAR(20) NOT NULL,
    CORREO VARCHAR(100) UNIQUE NOT NULL
);

-- Tabla DETALLE_VENTA
CREATE TABLE DETALLE_VENTA (
	CANTIDAD INT,
    PRECIO_TOTAL INT,
    IDVENTA INT,
    IDLIBRO INT
);

-- Tabla PAGOS
CREATE TABLE PAGOS (
	IDPAGO INT PRIMARY KEY AUTO_INCREMENT,
    IDCLIENTE INT,
    FECHA DATETIME,
    TYPO ENUM("EFECTIVO","DEBITO","CREDITO")
);

-- FOREIGN KEYS

-- EMPLEADO

ALTER TABLE EMPLEADO
    ADD CONSTRAINT FK_EMP_CLIENTE
    FOREIGN KEY (IDSUCURSAL) REFERENCES SUCURSAL(IDSUCURSAL);
    
-- LIBRO

ALTER TABLE LIBRO
    ADD CONSTRAINT FK_LIBRO_SUCURSAL
    FOREIGN KEY (IDSUCURSAL) REFERENCES SUCURSAL(IDSUCURSAL);
    
ALTER TABLE LIBRO
    ADD CONSTRAINT FK_LIBRO_PROVEEDOR
    FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDOR(IDPROVEEDOR);    
    
-- VENTA

ALTER TABLE VENTA
    ADD CONSTRAINT FK_VENTA_CLIENTE
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE VENTA
    ADD CONSTRAINT FK_VENTA_LIBRO
    FOREIGN KEY (IDLIBRO) REFERENCES LIBRO(IDLIBRO);

ALTER TABLE VENTA
    ADD CONSTRAINT FK_VENTA_EMPLEADO
    FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO (IDEMPLEADO);
    
ALTER TABLE VENTA
    ADD CONSTRAINT FK_VENTA_TIPOVENTA
    FOREIGN KEY (IDTIPOVENTA) REFERENCES TIPOVENTA (IDTIPOVENTA);
    
ALTER TABLE SUCURSAL
	ADD CONSTRAINT FK_SUCURSAL_GERENTE
    FOREIGN KEY (IDGERENTE) REFERENCES GERENTE (IDGERENTE);
    
ALTER TABLE DETALLE_VENTA
	ADD CONSTRAINT FK_DETALLE_VENTA_VENTA
    FOREIGN KEY (IDVENTA) REFERENCES VENTA (IDVENTA);
    
ALTER TABLE DETALLE_VENTA
	ADD CONSTRAINT FK_DETALLE_VENTA_LIBRO
    FOREIGN KEY (IDLIBRO) REFERENCES LIBRO (IDLIBRO);
    
ALTER TABLE PAGOS
	ADD CONSTRAINT FK_PAGOS_CLIENTE
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE);